delete  from Account
delete from AdvancedSalary
delete from AppPages
delete from CashBookLead
delete from CashSummary
delete from CustomerDRNote
delete from CustomerLead
delete from CustomerReceipt
delete from ExpenceTransaction
delete from ExpenceType
delete from Stock_OderDetail
delete from StockLead
delete from ProductStock
delete from Products
delete from ProductSubcategory
delete from ProductCategory
delete from ProductGroup
delete from TblShelf
delete from Purchase_OrderDetail
delete from PurchaseOrder
delete from Sale_OrderDetail
delete from Sale_Orders
delete from SupplierCRNote
delete from SupplierLead
delete from SupplierPayment
delete from Emplyee
delete from Customer
delete from Supplier